import AppKit

/// Polls NSPasteboard.general via changeCount — the only public mechanism on macOS.
/// Each tick reads ONLY changeCount (an integer fetch: no content access, no privacy alert).
/// Content is read exclusively after a change passes the full filter pipeline (spec §5).
@MainActor
final class ClipboardWatcher {
    /// Marker types that must never be recorded (spec §6.1), lowercased for comparison.
    /// Seeded from the nspasteboard.org convention plus Maccy's vendor ignore list.
    static let sensitiveMarkerTypes: Set<String> = [
        "org.nspasteboard.concealedtype",
        "org.nspasteboard.transienttype",
        "org.nspasteboard.autogeneratedtype",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.transientpasteboardtype",
        "pasteboard generator type",
        "net.antelle.keeweb",
    ]

    /// Yoink-style name heuristic: frontmost apps whose NAME contains one of these
    /// fragments are treated as password managers even when their bundle ID is unknown
    /// (new vendors, renamed apps). Kept short and high-precision.
    static let sensitiveAppNameFragments = ["password", "passwort", "keepass", "keychain"]

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int

    private let secureInput: SecureInputMonitor
    private let sourceTracker: SourceAppTracker

    // Dependencies injected as closures to keep the watcher free of settings/UI knowledge.
    var isCaptureAllowed: () -> Bool = { true }
    /// Self-write suppression (spec §5.1): PasteController records its own write's changeCount.
    var shouldIgnoreChangeCount: (Int) -> Bool = { _ in false }
    var excludedBundleIDs: () -> Set<String> = { [] }
    var maxItemSizeBytes: () -> Int = { 1_000_000 }
    var maxImageSizeBytes: () -> Int = { 25_000_000 }
    var maxFileSizeBytes: () -> Int = { 50_000_000 }
    var captureImagesEnabled: () -> Bool = { true }
    var captureFilesEnabled: () -> Bool = { true }
    /// Setting-gated heuristic net for password-manager browser extensions (spec §6.4):
    /// their copies carry no concealed marker and are attributed to the browser.
    var skipPasswordLikeText: () -> Bool = { true }
    var onCapture: (_ content: String, _ sourceApp: NSRunningApplication?) -> Void = { _, _ in }
    /// A captured image: raw bytes + its UTI.
    var onCaptureImage: (_ data: Data, _ uti: String, _ sourceApp: NSRunningApplication?) -> Void = { _, _, _ in }
    /// Captured files: (display name, UTI, bytes) per file.
    var onCaptureFiles: (_ files: [(name: String, uti: String, data: Data)], _ sourceApp: NSRunningApplication?) -> Void = { _, _ in }
    var onSecureInputStuckChanged: (Bool) -> Void = { _ in }

    init(secureInput: SecureInputMonitor, sourceTracker: SourceAppTracker) {
        self.secureInput = secureInput
        self.sourceTracker = sourceTracker
        lastChangeCount = pasteboard.changeCount
    }

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        // Skip whatever was on the pasteboard before monitoring started.
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.tick()
            }
        }
        timer.tolerance = 0.15 // allows timer coalescing for battery (spec §5)
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Pause stops the timer entirely, not just the handler (spec §5).
    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        // Secure-input state is re-evaluated EVERY tick, before any gating — otherwise a
        // "stuck" flag could never clear once it blocked capture (the flag's only writer
        // is this poll), and capture would stay dead until relaunch.
        let secure = secureInput.check()
        onSecureInputStuckChanged(secure.stuck)

        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        // 1. Self-write suppression — our own paste-from-history writes are not history events.
        guard !shouldIgnoreChangeCount(count) else { return }

        // 2. Pause / privacy state.
        guard isCaptureAllowed() else { return }

        // 3. Secure input (password field / sudo prompt focused) — never record.
        guard !secure.active else { return }

        // 4. Sensitive marker types — type inspection only, never triggers a content read.
        let types = pasteboard.types ?? []
        guard !Self.containsSensitiveMarker(types) else { return }

        // 5. Excluded app (best-effort: frontmost app sampled in this same tick, spec §5).
        //    Matched by bundle ID, with an app-NAME fallback for unknown password managers.
        let sourceApp = sourceTracker.bestGuessSourceApp()
        if let bundleID = sourceApp?.bundleIdentifier,
           excludedBundleIDs().contains(bundleID) {
            return
        }
        if Self.isSensitiveAppName(sourceApp?.localizedName) {
            return
        }

        // 6. Content read, by kind priority FILE > IMAGE > TEXT. A Finder copy carries both
        //    a file URL and its path string (the user copied the file, not the path); a
        //    browser image copy carries the image plus alt-text. Cheap reads only on main;
        //    heavy thumbnail/encrypt/payload work happens off-main in ClipboardStore.

        // 6a. FILE — once this is a file copy we COMMIT to file-kind and return regardless of
        //     whether the read succeeds. A rejected file (too big, unreadable, a directory)
        //     must NOT fall through to the text branch, where the pasteboard's path string
        //     would leak the file name into history.
        if captureFilesEnabled(), types.contains(.fileURL) {
            if let files = readFiles(maxTotalBytes: maxFileSizeBytes()), !files.isEmpty {
                onCaptureFiles(files, sourceApp)
            }
            return
        }

        // 6b. IMAGE
        if captureImagesEnabled(), let image = readImage(maxBytes: maxImageSizeBytes()) {
            onCaptureImage(image.data, image.uti, sourceApp)
            return
        }

        // 6c. TEXT (v1 path, byte-for-byte)
        guard types.contains(.string),
              let content = pasteboard.string(forType: .string) else { return }
        guard !content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        guard content.utf8.count <= maxItemSizeBytes() else { return }

        // Password-shaped text (catches browser-extension copies the marker check cannot
        // see — e.g. Norton/1Password/Bitwarden extensions in Chrome/Safari).
        if skipPasswordLikeText(), SensitiveTextDetector.looksLikePassword(content) {
            return
        }

        onCapture(content, sourceApp)
    }

    /// Image UTIs we capture, in preference order (lossless first).
    private static let imageTypes: [NSPasteboard.PasteboardType] = [
        .png,
        .tiff,
        NSPasteboard.PasteboardType("public.jpeg"),
        NSPasteboard.PasteboardType("public.heic"),
    ]

    /// Reads the best available image representation, rejecting over-cap data before any work.
    private func readImage(maxBytes: Int) -> (data: Data, uti: String)? {
        let available = pasteboard.types ?? []
        for type in Self.imageTypes where available.contains(type) {
            // `continue` (not return) so an over-cap/empty representation doesn't abort the
            // scan — a smaller acceptable representation (e.g. TIFF when PNG is huge) can win.
            guard let data = pasteboard.data(forType: type),
                  !data.isEmpty, data.count <= maxBytes else { continue }
            return (data, type.rawValue)
        }
        return nil
    }

    /// Reads regular files (not directories) copied to the pasteboard, with their bytes.
    /// Returns nil if any read fails or the total exceeds the cap.
    private func readFiles(maxTotalBytes: Int) -> [(name: String, uti: String, data: Data)]? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
              !urls.isEmpty else { return nil }

        var result: [(name: String, uti: String, data: Data)] = []
        var total = 0
        for url in urls {
            var isDirectory: ObjCBool = false
            guard FileManager.default.fileExists(atPath: url.path, isDirectory: &isDirectory),
                  !isDirectory.boolValue else {
                return nil // directories/bundles deferred to a later version
            }
            // Reject by DECLARED size before reading, so we never load a multi-GB file into
            // RAM just to discover it's over the cap.
            let declared = (try? url.resourceValues(forKeys: [.fileSizeKey]))?.fileSize ?? 0
            total += declared
            guard total <= maxTotalBytes else { return nil }
            guard let data = try? Data(contentsOf: url) else { return nil }
            let uti = (try? url.resourceValues(forKeys: [.contentTypeKey]))?.contentType?.identifier
                ?? "public.data"
            result.append((url.lastPathComponent, uti, data))
        }
        return result
    }

    static func containsSensitiveMarker(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains { sensitiveMarkerTypes.contains($0.rawValue.lowercased()) }
    }

    static func isSensitiveAppName(_ name: String?) -> Bool {
        guard let name = name?.lowercased() else { return false }
        return sensitiveAppNameFragments.contains { name.contains($0) }
    }
}
