import AppKit

/// Polls NSPasteboard.general via changeCount — the only public mechanism on macOS.
/// Each tick reads ONLY changeCount (an integer fetch: no content access, no privacy alert).
/// Content is read exclusively after a change passes the full filter pipeline (spec §5).
@MainActor
final class ClipboardWatcher {
    /// Marker types that must never be recorded (spec §6.1), lowercased for comparison.
    /// Seeded from the nspasteboard.org convention plus Maccy's vendor ignore list.
    static let sensitiveMarkerTypes: Set<String> = [
        "org.nspasteboard.concealedtype",
        "org.nspasteboard.transienttype",
        "org.nspasteboard.autogeneratedtype",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.transientpasteboardtype",
        "pasteboard generator type",
        "net.antelle.keeweb",
    ]

    /// Yoink-style name heuristic: frontmost apps whose NAME contains one of these
    /// fragments are treated as password managers even when their bundle ID is unknown
    /// (new vendors, renamed apps). Kept short and high-precision.
    static let sensitiveAppNameFragments = ["password", "passwort", "keepass", "keychain"]

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int

    private let secureInput: SecureInputMonitor
    private let sourceTracker: SourceAppTracker

    // Dependencies injected as closures to keep the watcher free of settings/UI knowledge.
    var isCaptureAllowed: () -> Bool = { true }
    /// Self-write suppression (spec §5.1): PasteController records its own write's changeCount.
    var shouldIgnoreChangeCount: (Int) -> Bool = { _ in false }
    var excludedBundleIDs: () -> Set<String> = { [] }
    var maxItemSizeBytes: () -> Int = { 1_000_000 }
    /// Setting-gated heuristic net for password-manager browser extensions (spec §6.4):
    /// their copies carry no concealed marker and are attributed to the browser.
    var skipPasswordLikeText: () -> Bool = { true }
    var onCapture: (_ content: String, _ sourceApp: NSRunningApplication?) -> Void = { _, _ in }
    var onSecureInputStuckChanged: (Bool) -> Void = { _ in }

    init(secureInput: SecureInputMonitor, sourceTracker: SourceAppTracker) {
        self.secureInput = secureInput
        self.sourceTracker = sourceTracker
        lastChangeCount = pasteboard.changeCount
    }

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        // Skip whatever was on the pasteboard before monitoring started.
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.tick()
            }
        }
        timer.tolerance = 0.15 // allows timer coalescing for battery (spec §5)
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Pause stops the timer entirely, not just the handler (spec §5).
    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        // Secure-input state is re-evaluated EVERY tick, before any gating — otherwise a
        // "stuck" flag could never clear once it blocked capture (the flag's only writer
        // is this poll), and capture would stay dead until relaunch.
        let secure = secureInput.check()
        onSecureInputStuckChanged(secure.stuck)

        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        // 1. Self-write suppression — our own paste-from-history writes are not history events.
        guard !shouldIgnoreChangeCount(count) else { return }

        // 2. Pause / privacy state.
        guard isCaptureAllowed() else { return }

        // 3. Secure input (password field / sudo prompt focused) — never record.
        guard !secure.active else { return }

        // 4. Sensitive marker types — type inspection only, never triggers a content read.
        let types = pasteboard.types ?? []
        guard !Self.containsSensitiveMarker(types) else { return }

        // 5. Excluded app (best-effort: frontmost app sampled in this same tick, spec §5).
        //    Matched by bundle ID, with an app-NAME fallback for unknown password managers.
        let sourceApp = sourceTracker.bestGuessSourceApp()
        if let bundleID = sourceApp?.bundleIdentifier,
           excludedBundleIDs().contains(bundleID) {
            return
        }
        if Self.isSensitiveAppName(sourceApp?.localizedName) {
            return
        }

        // 6. Content read — only now, and only if a string type is actually present.
        guard types.contains(.string),
              let content = pasteboard.string(forType: .string) else { return }
        guard !content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        guard content.utf8.count <= maxItemSizeBytes() else { return }

        // 7. Password-shaped text (catches browser-extension copies the marker check
        //    cannot see — e.g. Norton/1Password/Bitwarden extensions in Chrome/Safari).
        if skipPasswordLikeText(), SensitiveTextDetector.looksLikePassword(content) {
            return
        }

        // 8–9. Dedup + capture happen in ClipboardStore.
        onCapture(content, sourceApp)
    }

    static func containsSensitiveMarker(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains { sensitiveMarkerTypes.contains($0.rawValue.lowercased()) }
    }

    static func isSensitiveAppName(_ name: String?) -> Bool {
        guard let name = name?.lowercased() else { return false }
        return sensitiveAppNameFragments.contains { name.contains($0) }
    }
}
